global:
  mode: img2img
  prompt: "a beautiful minecraft landscape, lights and shadows"
  negative_prompt: "ugly"
  model_name_or_path: "SG161222/Realistic_Vision_V2.0"
  steps: 20
  width: 768
  height: 768
  seed: -1
  input_image: qrcode

controlnet_units:
  - brightness:
      model_name: ioclab/control_v1p_sd15_brightness
      #module: none not implemented yet
      weight: 0.35
      start: 0.0
      end: 1.0

  - tile:
      model: lllyasviel/control_v11f1e_sd15_tile
      #module: none not implemented yet
      weight: 0.5
      start: 0.35
      end: 0.70

qrcode:
  text: "https://koll.ai"
  error_correction: high # [low, medium, quart, high]
  box_size: 10
  border: 4
  fill_color: black
  back_color: white